### ISSUE TITLE
Language Server crashing repeatedly

### ISSUE THREAD

**Issue by contentfree** [Hennamann/ExtendScript-for-Visual-Studio-Code#25]
Installed this extension today and an error notice popped up:
> The ExtendScript Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

**Comment by bluehz** [comment]
I am seeing this as well on Mac / Monterey. Several attempts to fix have failed.

**Comment by stenza** [comment]
Same here, OSX Monterey, Apple M1

**Comment by Hennamann** [comment]
Sorry for replying so late to this, just got a Apple Silicon mac myself, and can´t seem to reproduce the issue... Are you doing anything in particular in regards to extendscript when you get the message about the language server crashing?

**Comment by stenza** [comment]
Simply start VSC (without using Rosetta mode) and immediately got the message in the corner.
Monterey, 12.3.1, M1 PRO

<img width="471" alt="Screenshot 2022-04-17 at 20 06 26" src="https://user-images.githubusercontent.com/5930148/163728914-c1ddd799-5709-479a-b046-bd10eade4329.png">

**Comment by bluehz** [comment]
I get the exact same message and I'm on Intel Mac. I've prob spent 2 hours
trying to troubleshoot with no luck.

**Comment by stenza** [comment]
Interesting, because If I run it with using Rosetta, it runs like a charm...

**Comment by Hennamann** [comment]
Odd, i am able to reproduce it now, but it seems a bit random on my end. Either way i believe i have a better way to get intellisense/language server support into the extension, just need to test it. I'll try to get a beta build posted in this issue tomorrow (UTC+2) for testing.

**Comment by Hennamann** [comment]
Alright, here's the beta/alpha release, would be great if some of you could test this so i can get it released to the marketplace. https://github.com/Hennamann/ExtendScript-for-Visual-Studio-Code/releases/tag/v1.3.0-alpha
To install it just go to the extensions page in vscode and use the context menu in the upper right corner and select "Install from VSIX" and choose the downloaded VSIX file.

**Comment by bluehz** [comment]
Installed - will test drive later and let you know. Thx!

**Comment by stenza** [comment]
Installed - no crash. Tried my longest file, with and without Rosetta.
Thanks, now I think we can forget Rosetta mode.

**Comment by Hennamann** [comment]
This has now been fixed with the latest release of the extension (1.3.0), which has now also been published to the vscode marketplace. 

If you find any issues with the update surrounding intellisense/code completion, please post a comment so i can reopen this issue instead of creating a new one.

**Comment by bluehz** [comment]
Sorry I thought I sent this last night - still not fixed on intel with that
Beta I tried - I will install the release and see if it matters.
[image:
Font_Scripts_savedSearch_—__InDesign_Script_Dev_VSCode__Workspace_.jpg]
